// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://idvetrnsvuqarzdriitl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlkdmV0cm5zdnVxYXJ6ZHJpaXRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3NDA1MDMsImV4cCI6MjA3MzMxNjUwM30.ONjVizbj-SRkMRBhJaHQhxRjXkaqn6IUj1Stlir6J_Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});